### ISSUE TITLE
Disease mappings content not loaded

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/mapping-commons.github.io#2]
[Disease mapping content](https://github.com/mapping-commons/mapping-commons.github.io/blob/main/mapping-server.yml#L7) not loaded.. Maybe the problem is with the fact that http URLs are used?

<img width="729" alt="image" src="https://user-images.githubusercontent.com/7070631/199840970-80213399-b9f1-47dd-8883-e8171e1b49db.png">

Tragic. Annoying.

**Comment by souzadevinicius** [comment]
Modern browsers don't allow mixed content (some resources from HTTPS and others from HTTP)
The ideal scenario is to serve the URL mentioned in the HTTPS context.

More info about this error:
---
What is mixed content and what are the risks?
HTTP is a system for transmitting information from a web server to your browser. HTTP is not secure, so when you visit a page served over HTTP, your connection is open for eavesdropping and [man-in-the-middle attacks](https://wikipedia.org/wiki/Man-in-the-middle_attack). Most websites are served over HTTP because they don't involve passing sensitive information back and forth and do not need to be secured.

When you visit a page fully transmitted over HTTPS, such as your bank, you'll see a padlock icon Fx89Padlock in the address bar (for details, see [How do I tell if my connection to a website is secure?](https://support.mozilla.org/en-US/kb/how-do-i-tell-if-my-connection-is-secure)). This means that your connection is authenticated and encrypted, and thus safeguarded from both eavesdroppers and man-in-the-middle attacks.

However, if the HTTPS page you visit includes HTTP content, the HTTP portion can be read or modified by attackers, even though the main page is served over HTTPS. When an HTTPS page has HTTP content, we call that content “mixed”. The page you are visiting is only partially encrypted and even though it appears to be secure, it isn't. For more information about mixed content (active and passive), see [this blog post](https://blog.mozilla.org/tanvi/2013/04/10/mixed-content-blocking-enabled-in-firefox-23).

**Comment by matentzn** [comment]
Will be solved by https://github.com/mapping-commons/mapping-commons.github.io/issues/4

**Comment by matentzn** [comment]
Fixed.
